# Generated by Django 2.2.6 on 2019-11-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='compeleted',
            new_name='completed',
        ),
    ]
